sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t stojanovskimilan/docker-react -f Dockerfile.dev .

script: 
  - docker run -p 3000:3000 -e CI=true stojanovskimilan/docker-react npm run test
  

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "test-app"
  env: "Test-app-env"
  bucket_name: "elasticbeanstalk-eu-west-2-657503446209"
  bucket_path: "test-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
