sudo: required
services:
  - docker

before_install:
  - docker build -t stojanovskimilan/docker-react -f Dockerfile.dev .

script: 
  - docker run stojanovskimilan/docker-react npm run test -- --coverage
